server {
    listen 80;
    index index.php;
    root /var/www/html/public;

    location / {
        try_files $uri @pachybase_front_controller;
    }

    location @pachybase_front_controller {
        rewrite ^ /index.php?$query_string last;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_read_timeout 60s;
    }
}
